#!/usr/bin/env bash
# ensure SSH is installed
sudo apt install ssh

# enable root login over SSH
awk '{ gsub ("#PermitRootLogin prohibit-password", "PermitRootLogin yes", $0); print}' /etc/ssh/sshd_config > temp.txt && mv temp.txt /etc/ssh/sshd_config

# restart SSH
service ssh restart

# paste status of SSH
sudo systemctl status sshd

quit
echo 'I haven't yet found a way to make the program exit itself and return you to the command line. So just hit the Q key and it'll take you back safely.' 
