#!/usr/bin/env bash
# Tor
cd
cd
wget  -P ~/Desktop/ "https://www.torproject.org/dist/torbrowser/8.5.4/tor-browser-linux64-8.5.4_en-US.tar.xz"
# gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org
# gpg --output ./tor.keyring --export 0xEF6E286DDA85EA2A4BA7DE684E2C6E8793298290
# gpgv --keyring ./tor.keyring tor-browser-linux64-8.5.4_en-US.tar.xz{.asc,}
tar -xf ~/Desktop/tor-browser-linux64-8.5.4_en-US.tar.xz
cd Desktop
./start-tor-browser.desktop --register-app
rm tor-browser-linux64-8.5.4_en-US.tar.xz

# Spotify, because yes
sudo snap install spotify
# Since Spotify on Linux is not officially supported, there's no way to verify checksums. Just... hope. 

# Wireshark
wget -P ~/Desktop/ "https://2.na.dl.wireshark.org/src/wireshark-3.0.3.tar.xz"
# Okay, there's a way to verify Wireshark's checksum and the signature of the checksum, something about GPG, but I can't figure 
# it out. SO I guess for now you're getting a possibly corrupted file to play with :) You're welcome. 
tar -xf ~/Desktop/wireshark-3.0.3.tar.xz
rm wireshark-3.0.3.tar.xz
