#!/usr/bin/env bash
# disable Wayland display server by uncommenting "WaylandEnable=false" 
sudo sed -i 's/#Way/Way/g' /etc/gdm3/custom.conf
echo 'Finished disabling Wayland display server.'

# install xfce
sudo apt-get -y install xfce4
echo 'Finished installing xfce4.'

# enable tap-to-click in xfce
xfconf-query -c pointers -p /Atmel_maXTouch_Touchpad/Properties/libinput_Tapping_Enabled -n -t int -s 1
echo 'Finished enabling tap-to-click in xfce desktop environment.'
